# 学生登录测试



POST  http://106.12.195.114:8081/user/login
content-type: application/json

{
  "username": "1713010101",
  "password": "111111"
}

###

# 教师登录测试

POST http://106.12.195.114:8081/user/login
content-type: application/json

{
  "username": "T1514010101",
  "password": "111111"
}




###

# 根据班级试卷

GET http://localhost:8081/page/exams/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzEzMDEwMTAxIiwiY2xhc3NJZCI6MSwidXNlcklkIjo4MTEsImlhdCI6MTU0ODI5NzUyOSwiZXhwIjoxNTQ4OTAyMzI5fQ.LLJQA6CXqofcBY8xP-PE8KESsYKJlqhXT37sG_0eAXo

###

# 根据 班级试卷id 和 试卷id 查询考卷
# /page/exam
GET http://localhost:8081/page/exam
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzEzMDEwMTAxIiwiY2xhc3NJZCI6MSwidXNlcklkIjo4MTEsInJvbGVzIjpbInN0dWRlbnQiXSwiaWF0IjoxNTU3MzE4MzgyLCJleHAiOjE1NTc5MjMxODJ9.Q2P0__ffkTUn15AR09ZmThWoxTnCsFsePGtHBMORLMw

{
  "classId": 1,
  "pageId": 1
}

###

GET http://localhost:8081/class/getClass
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzEzMDEwMTAxIiwiY2xhc3NJZCI6MSwidXNlcklkIjo4MTEsInJvbGVzIjpbInN0dWRlbnQiXSwiaWF0IjoxNTU0OTc3ODMxLCJleHAiOjE1NTU1ODI2MzF9.Qf-8NBDxoSZk8CEf1kOMdIJeV3vgvEJsBfA__t5sQRg

###

GET http://localhost:8081/course/getCourse
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzEzMDEwMTAxIiwiY2xhc3NJZCI6MSwidXNlcklkIjo4MTEsInJvbGVzIjpbInN0dWRlbnQiXSwiaWF0IjoxNTU0OTc3ODMxLCJleHAiOjE1NTU1ODI2MzF9.Qf-8NBDxoSZk8CEf1kOMdIJeV3vgvEJsBfA__t5sQRg

###

GET http://localhost:8081/topic/getTopic
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzEzMDEwMTAxIiwiY2xhc3NJZCI6MSwidXNlcklkIjo4MTEsInJvbGVzIjpbInN0dWRlbnQiXSwiaWF0IjoxNTU0OTc3ODMxLCJleHAiOjE1NTU1ODI2MzF9.Qf-8NBDxoSZk8CEf1kOMdIJeV3vgvEJsBfA__t5sQRg

{
  "id": 1,
  "name": "Xxx"
}

###
GET http://localhost:8081/class/passed/1/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzEzMDEwMTAxIiwiY2xhc3NJZCI6MSwidXNlcklkIjo4MTEsInJvbGVzIjpbInN0dWRlbnQiXSwiaWF0IjoxNTU0OTc3ODMxLCJleHAiOjE1NTU1ODI2MzF9.Qf-8NBDxoSZk8CEf1kOMdIJeV3vgvEJsBfA__t5sQRg


###
#/teacher/{teacherId}
GET http://106.12.195.114:8081/course/teacher/31
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJUMTUxNDAxMDEwMSIsInBvc2l0aW9uSWQiOjEsInVzZXJJZCI6MTU1NSwicm9sZXMiOlsidGVhY2hlciJdLCJpYXQiOjE1NTU1NTc1ODUsImV4cCI6MTU1NjE2MjM4NX0.J4xWfDxYTeBDn0zY3NwqJi5AKmXMVzZfs_qv6X0OZnY

###

POST http://106.12.195.114:9000/code
content-type: application/json

{
  "filepath":"d:/datafile/test.cpp",
  "outpath":"d:/data/test.cpp",
  "filename":"123.cpp",
  "testSet":"{'datas': [{'input': '#$%1,2%$#','output': '#$%3%$#'},{'input': '#$%3,6%$#','output': '#$%9%$#'}]}",
  "limitetime":3
}

###

GET http://localhost:8081/class/average/1/1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzEzMDEwMTAxIiwiY2xhc3NJZCI6MSwidXNlcklkIjo4MTEsInJvbGVzIjpbInN0dWRlbnQiXSwiaWF0IjoxNTU3MzE4MzgyLCJleHAiOjE1NTc5MjMxODJ9.Q2P0__ffkTUn15AR09ZmThWoxTnCsFsePGtHBMORLMw

###
