# 学生登录测试

POST http://localhost:8081/user/login
content-type: application/json

{
  "username": "1713010101",
  "password": "111111"
}

###

# 教师登录测试

POST http://localhost:8081/user/login
content-type: application/json

{
  "username": "T1514010101",
  "password": "111111"
}




###

# 根据班级试卷

GET http://localhost:8081/page/exams/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzEzMDEwMTAxIiwiY2xhc3NJZCI6MSwidXNlcklkIjo4MTEsImlhdCI6MTU0ODI5NzUyOSwiZXhwIjoxNTQ4OTAyMzI5fQ.LLJQA6CXqofcBY8xP-PE8KESsYKJlqhXT37sG_0eAXo

###

# 根据 班级试卷id 和 试卷id 查询考卷
# /page/exam
GET http://localhost:8081/page/exam
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNzEzMDEwMTAxIiwiY2xhc3NJZCI6MSwidXNlcklkIjo4MTEsImlhdCI6MTU0ODI5NzUyOSwiZXhwIjoxNTQ4OTAyMzI5fQ.LLJQA6CXqofcBY8xP-PE8KESsYKJlqhXT37sG_0eAXo

{
  "classId": 1,
  "pageId": 1
}

###



