spring:
  rabbitmq:
    host: 193.112.6.35
    port: 5672
    username: admin
    password: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.154.79:3306/db_online_education?useUnicode=true&amp;characterEncoding=utf-8
    username: zhongpro
    password: zhongpro
  jpa:
    database: mysql
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8080

logging:
  level: off
